<?php

namespace App\Services;

use App\Models\Booking;
use App\Models\Court;
use App\Models\Payment;
use App\Models\SiteSettings;
use App\Models\User;
use Illuminate\Support\Carbon;
use Symfony\Component\HttpFoundation\StreamedResponse;

class ReportExportService
{
    public const DAILY_OPERATING_HOURS = 16;

    /**
     * Resolve date range parameters for the given period identifier.
     */
    public function resolveDateRange(string $period): array
    {
        $now = Carbon::now();

        return match ($period) {
            'this_day', 'today' => [
                'start' => Carbon::today()->startOfDay(),
                'end' => Carbon::today()->endOfDay(),
                'label' => 'This Day (' . Carbon::today()->format('Y-m-d') . ')',
                'period_key' => 'this_day',
                'days' => 1,
            ],
            'last_month' => [
                'start' => $now->copy()->subMonth()->startOfMonth()->startOfDay(),
                'end' => $now->copy()->subMonth()->endOfMonth()->endOfDay(),
                'label' => 'Last Month (' . $now->copy()->subMonth()->format('F Y') . ')',
                'period_key' => 'last_month',
                'days' => $now->copy()->subMonth()->daysInMonth,
            ],
            'this_year' => [
                'start' => $now->copy()->startOfYear()->startOfDay(),
                'end' => $now->copy()->endOfYear()->endOfDay(),
                'label' => 'This Year (' . $now->year . ')',
                'period_key' => 'this_year',
                'days' => $now->isLeapYear() ? 366 : 365,
            ],
            default => [
                'start' => $now->copy()->startOfMonth()->startOfDay(),
                'end' => $now->copy()->endOfMonth()->endOfDay(),
                'label' => 'This Month (' . $now->format('F Y') . ')',
                'period_key' => 'this_month',
                'days' => $now->daysInMonth,
            ],
        };
    }

    /**
     * Export Overall Operations Report.
     */
    public function exportOverall(string $period, User $user): StreamedResponse
    {
        $range = $this->resolveDateRange($period);
        $startDate = $range['start']->toDateString();
        $endDate = $range['end']->toDateString();

        $bookings = Booking::with(['court', 'user', 'payments'])
            ->whereBetween('date', [$startDate, $endDate])
            ->orderBy('date')
            ->orderBy('start_time')
            ->get();

        $payments = Payment::whereBetween('date', [$startDate, $endDate])->get();
        $paidPayments = $payments->where('payment_status', 'paid');

        $totalRevenue = (float) $paidPayments->sum('amount');
        $onlineRevenue = (float) $paidPayments->where('payment_method', 'paymongo')->sum('amount');
        $cashRevenue = (float) $paidPayments->where('payment_method', 'cash')->sum('amount');

        $activeBookings = $bookings->where('booking_status', '!=', 'cancelled');
        $bookedHours = (float) $activeBookings->sum(fn ($b) => $this->calculateBookingHours($b));

        $availableCourtsCount = max(Court::where('court_status', 'available')->count(), 1);
        $capacityHours = $availableCourtsCount * self::DAILY_OPERATING_HOURS * $range['days'];
        $utilizationRate = $capacityHours > 0 ? min(round(($bookedHours / $capacityHours) * 100, 1), 100.0) : 0.0;

        $filename = 'overall-report-' . $range['period_key'] . '-' . date('Y-m-d') . '.csv';

        return response()->streamDownload(function () use ($range, $user, $bookings, $activeBookings, $totalRevenue, $onlineRevenue, $cashRevenue, $bookedHours, $capacityHours, $utilizationRate) {
            $handle = fopen('php://output', 'w');
            // Write UTF-8 BOM for Excel compatibility
            fwrite($handle, "\xEF\xBB\xBF");

            $siteName = SiteSettings::first()->system_name ?? 'KYMNET';

            fputcsv($handle, [$siteName . ' - OVERALL OPERATIONS REPORT']);
            fputcsv($handle, ['Reporting Period', $range['label']]);
            fputcsv($handle, ['Generated At', Carbon::now()->toDateTimeString()]);
            fputcsv($handle, ['Generated By', $user->name . ' (' . strtoupper($user->role) . ')']);
            fputcsv($handle, []);

            // KPI Executive Summary
            fputcsv($handle, ['--- EXECUTIVE SUMMARY METRICS ---']);
            fputcsv($handle, ['Metric', 'Value']);
            fputcsv($handle, ['Total Bookings Logged', $bookings->count()]);
            fputcsv($handle, ['Confirmed / Active Bookings', $bookings->whereIn('booking_status', ['confirmed', 'show'])->count()]);
            fputcsv($handle, ['Pending Bookings', $bookings->where('booking_status', 'pending')->count()]);
            fputcsv($handle, ['Cancelled Bookings', $bookings->where('booking_status', 'cancelled')->count()]);
            fputcsv($handle, ['No-Show Bookings', $bookings->where('booking_status', 'no_show')->count()]);
            fputcsv($handle, ['Online Bookings', $bookings->where('booking_type', 'online')->count()]);
            fputcsv($handle, ['Walk-In Bookings', $bookings->where('booking_type', 'walk_in')->count()]);
            fputcsv($handle, ['Total Collected Revenue (PHP)', number_format($totalRevenue, 2, '.', '')]);
            fputcsv($handle, ['Online Revenue (PHP)', number_format($onlineRevenue, 2, '.', '')]);
            fputcsv($handle, ['Cash / Counter Revenue (PHP)', number_format($cashRevenue, 2, '.', '')]);
            fputcsv($handle, ['Total Court Hours Booked', number_format($bookedHours, 2, '.', '')]);
            fputcsv($handle, ['Facility Capacity Hours', $capacityHours]);
            fputcsv($handle, ['Facility Utilization Rate (%)', $utilizationRate . '%']);
            fputcsv($handle, []);

            // Detailed Bookings Table
            fputcsv($handle, ['--- ITEMIZED BOOKINGS LIST ---']);
            fputcsv($handle, [
                'Booking ID',
                'Reference Number',
                'Customer Name',
                'Customer Email',
                'Court Name',
                'Date',
                'Start Time',
                'End Time',
                'Duration (Hours)',
                'Booking Type',
                'Booking Status',
                'Amount (PHP)',
                'Payment Method',
                'Payment Status',
            ]);

            foreach ($bookings as $booking) {
                $payment = $booking->payments->first();
                $hours = $this->calculateBookingHours($booking);

                fputcsv($handle, [
                    $booking->id,
                    $booking->reference_number ?? ('BK-' . $booking->id),
                    $booking->user->name ?? $booking->customer_name ?? 'Guest Customer',
                    $booking->user->email ?? $booking->customer_email ?? 'N/A',
                    $booking->court->court_name ?? 'Court #' . $booking->court_id,
                    $booking->date,
                    $booking->start_time,
                    $booking->end_time,
                    number_format($hours, 2, '.', ''),
                    ucfirst(str_replace('_', ' ', $booking->booking_type ?? 'online')),
                    ucfirst($booking->booking_status),
                    $payment ? number_format((float) $payment->amount, 2, '.', '') : '0.00',
                    $payment ? ucfirst($payment->payment_method) : 'N/A',
                    $payment ? ucfirst($payment->payment_status) : 'N/A',
                ]);
            }

            fclose($handle);
        }, $filename, [
            'Content-Type' => 'text/csv; charset=UTF-8',
            'Content-Disposition' => "attachment; filename=\"{$filename}\"",
        ]);
    }

    /**
     * Export Financial and Revenue Audit Report.
     */
    public function exportFinancial(string $period, User $user): StreamedResponse
    {
        $range = $this->resolveDateRange($period);
        $startDate = $range['start']->toDateString();
        $endDate = $range['end']->toDateString();

        $payments = Payment::with(['booking.court', 'booking.user'])
            ->whereBetween('date', [$startDate, $endDate])
            ->orderBy('date')
            ->orderBy('created_at')
            ->get();

        $paidPayments = $payments->where('payment_status', 'paid');
        $totalPaidAmount = (float) $paidPayments->sum('amount');
        $paidCount = $paidPayments->count();
        $pendingPayments = $payments->where('payment_status', 'pending');
        $pendingCount = $pendingPayments->count();
        $pendingAmount = (float) $pendingPayments->sum('amount');

        $onlinePaid = $paidPayments->filter(fn ($p) => ($p->booking->booking_type ?? '') === 'online');
        $walkInPaid = $paidPayments->filter(fn ($p) => ($p->booking->booking_type ?? '') === 'walk_in');

        $methodBreakdown = $paidPayments->groupBy('payment_method')->map(function ($group) use ($totalPaidAmount) {
            $sum = (float) $group->sum('amount');
            return [
                'total' => $sum,
                'count' => $group->count(),
                'percent' => $totalPaidAmount > 0 ? round(($sum / $totalPaidAmount) * 100, 1) : 0.0,
            ];
        });

        $filename = 'financial-report-' . $range['period_key'] . '-' . date('Y-m-d') . '.csv';

        return response()->streamDownload(function () use ($range, $user, $payments, $totalPaidAmount, $paidCount, $pendingCount, $pendingAmount, $onlinePaid, $walkInPaid, $methodBreakdown) {
            $handle = fopen('php://output', 'w');
            fwrite($handle, "\xEF\xBB\xBF");

            $siteName = SiteSettings::first()->system_name ?? 'KYMNET';

            fputcsv($handle, [$siteName . ' - FINANCIAL & REVENUE AUDIT REPORT']);
            fputcsv($handle, ['Reporting Period', $range['label']]);
            fputcsv($handle, ['Generated At', Carbon::now()->toDateTimeString()]);
            fputcsv($handle, ['Generated By', $user->name . ' (' . strtoupper($user->role) . ')']);
            fputcsv($handle, []);

            // Summary Totals
            fputcsv($handle, ['--- FINANCIAL SUMMARY ---']);
            fputcsv($handle, ['Metric', 'Amount (PHP)', 'Transaction Count']);
            fputcsv($handle, ['Total Paid Revenue Collections', number_format($totalPaidAmount, 2, '.', ''), $paidCount]);
            fputcsv($handle, ['Online Bookings Revenue', number_format((float) $onlinePaid->sum('amount'), 2, '.', ''), $onlinePaid->count()]);
            fputcsv($handle, ['Walk-In Counter Revenue', number_format((float) $walkInPaid->sum('amount'), 2, '.', ''), $walkInPaid->count()]);
            fputcsv($handle, ['Pending / Unsettled Receivables', number_format($pendingAmount, 2, '.', ''), $pendingCount]);
            fputcsv($handle, [
                'Average Paid Transaction Value',
                $paidCount > 0 ? number_format($totalPaidAmount / $paidCount, 2, '.', '') : '0.00',
                '-',
            ]);
            fputcsv($handle, []);

            // Payment Methods Breakdown
            fputcsv($handle, ['--- PAYMENT METHOD BREAKDOWN ---']);
            fputcsv($handle, ['Payment Method', 'Total Collections (PHP)', 'Transaction Count', 'Share (%)']);
            foreach ($methodBreakdown as $method => $data) {
                fputcsv($handle, [
                    ucfirst((string) $method),
                    number_format($data['total'], 2, '.', ''),
                    $data['count'],
                    $data['percent'] . '%',
                ]);
            }
            fputcsv($handle, []);

            // Itemized Transaction Ledger
            fputcsv($handle, ['--- ITEMIZED PAYMENT LEDGER ---']);
            fputcsv($handle, [
                'Payment ID',
                'Payment Reference / Session',
                'Booking Reference',
                'Transaction Date',
                'Customer Name',
                'Customer Email',
                'Court',
                'Booking Type',
                'Amount (PHP)',
                'Payment Method',
                'Payment Status',
            ]);

            foreach ($payments as $payment) {
                $booking = $payment->booking;
                fputcsv($handle, [
                    $payment->id,
                    $payment->ref_num ?? $payment->checkout_session_id ?? ('PAY-' . $payment->id),
                    $booking ? ($booking->reference_number ?? ('BK-' . $booking->id)) : 'N/A',
                    $payment->date,
                    $booking->user->name ?? $booking->customer_name ?? 'Guest Customer',
                    $booking->user->email ?? $booking->customer_email ?? 'N/A',
                    $booking->court->court_name ?? 'N/A',
                    ucfirst(str_replace('_', ' ', $booking->booking_type ?? 'online')),
                    number_format((float) $payment->amount, 2, '.', ''),
                    ucfirst($payment->payment_method),
                    ucfirst($payment->payment_status),
                ]);
            }

            fclose($handle);
        }, $filename, [
            'Content-Type' => 'text/csv; charset=UTF-8',
            'Content-Disposition' => "attachment; filename=\"{$filename}\"",
        ]);
    }

    /**
     * Export Court Capacity and Utilization Report.
     */
    public function exportUtilization(string $period, User $user): StreamedResponse
    {
        $range = $this->resolveDateRange($period);
        $startDate = $range['start']->toDateString();
        $endDate = $range['end']->toDateString();

        $courts = Court::with(['bookings' => function ($q) use ($startDate, $endDate) {
            $q->where('booking_status', '!=', 'cancelled')
                ->whereBetween('date', [$startDate, $endDate])
                ->with('payments');
        }])->orderBy('court_name')->get();

        $days = $range['days'];
        $courtCapacity = self::DAILY_OPERATING_HOURS * $days;
        $totalCourts = $courts->count();
        $availableCourts = $courts->where('court_status', 'available')->count();
        $totalFacilityCapacity = max($availableCourts, 1) * $courtCapacity;

        $courtStats = $courts->map(function (Court $court) use ($courtCapacity) {
            $bookings = $court->bookings;
            $bookedHours = (float) $bookings->sum(fn ($b) => $this->calculateBookingHours($b));
            $rate = $courtCapacity > 0 ? min(round(($bookedHours / $courtCapacity) * 100, 1), 100.0) : 0.0;
            $revenue = (float) $bookings->flatMap->payments->where('payment_status', 'paid')->sum('amount');
            $revPach = $courtCapacity > 0 ? round($revenue / $courtCapacity, 2) : 0.0;
            $peakSlot = $this->determinePeakSlot($bookings);

            return [
                'court' => $court,
                'capacity_hours' => $courtCapacity,
                'booked_hours' => $bookedHours,
                'utilization_rate' => $rate,
                'sessions_count' => $bookings->count(),
                'revenue' => $revenue,
                'rev_pach' => $revPach,
                'peak_slot' => $peakSlot,
            ];
        });

        $totalFacilityBookedHours = (float) $courtStats->sum('booked_hours');
        $facilityUtilizationRate = $totalFacilityCapacity > 0
            ? min(round(($totalFacilityBookedHours / $totalFacilityCapacity) * 100, 1), 100.0)
            : 0.0;
        $totalFacilityRevenue = (float) $courtStats->sum('revenue');

        $filename = 'utilization-report-' . $range['period_key'] . '-' . date('Y-m-d') . '.csv';

        return response()->streamDownload(function () use ($range, $user, $courts, $courtStats, $days, $totalCourts, $availableCourts, $totalFacilityCapacity, $totalFacilityBookedHours, $facilityUtilizationRate, $totalFacilityRevenue) {
            $handle = fopen('php://output', 'w');
            fwrite($handle, "\xEF\xBB\xBF");

            $siteName = SiteSettings::first()->system_name ?? 'KYMNET';

            fputcsv($handle, [$siteName . ' - COURT UTILIZATION & CAPACITY REPORT']);
            fputcsv($handle, ['Reporting Period', $range['label']]);
            fputcsv($handle, ['Days in Period', $days]);
            fputcsv($handle, ['Generated At', Carbon::now()->toDateTimeString()]);
            fputcsv($handle, ['Generated By', $user->name . ' (' . strtoupper($user->role) . ')']);
            fputcsv($handle, []);

            // Facility Summary
            fputcsv($handle, ['--- FACILITY CAPACITY METRICS ---']);
            fputcsv($handle, ['Metric', 'Value']);
            fputcsv($handle, ['Total Courts in Facility', $totalCourts]);
            fputcsv($handle, ['Available Operating Courts', $availableCourts]);
            fputcsv($handle, ['Daily Operating Hours Per Court', self::DAILY_OPERATING_HOURS . ' Hours (6:00 AM - 10:00 PM)']);
            fputcsv($handle, ['Total Facility Capacity Hours', $totalFacilityCapacity . ' Hours']);
            fputcsv($handle, ['Total Hours Booked / Utilized', number_format($totalFacilityBookedHours, 2, '.', '') . ' Hours']);
            fputcsv($handle, ['Facility Utilization Rate (%)', $facilityUtilizationRate . '%']);
            fputcsv($handle, ['Total Revenue Generated by Fleet (PHP)', number_format($totalFacilityRevenue, 2, '.', '')]);
            fputcsv($handle, [
                'Facility RevPACH (Revenue Per Available Court Hour)',
                $totalFacilityCapacity > 0 ? 'PHP ' . number_format($totalFacilityRevenue / $totalFacilityCapacity, 2, '.', '') : 'PHP 0.00',
            ]);
            fputcsv($handle, []);

            // Per Court Breakdown
            fputcsv($handle, ['--- PER-COURT UTILIZATION BREAKDOWN ---']);
            fputcsv($handle, [
                'Court ID',
                'Court Name',
                'Status',
                'Hourly Rate (PHP)',
                'Operating Capacity (Hours)',
                'Actual Booked Hours',
                'Utilization Rate (%)',
                'Sessions Count',
                'Revenue Generated (PHP)',
                'RevPACH (PHP/Hour)',
                'Peak Time Slot',
            ]);

            foreach ($courtStats as $stat) {
                $court = $stat['court'];
                fputcsv($handle, [
                    $court->id,
                    $court->court_name,
                    ucfirst($court->court_status),
                    number_format((float) $court->price_per_hour, 2, '.', ''),
                    $stat['capacity_hours'],
                    number_format($stat['booked_hours'], 2, '.', ''),
                    $stat['utilization_rate'] . '%',
                    $stat['sessions_count'],
                    number_format($stat['revenue'], 2, '.', ''),
                    number_format($stat['rev_pach'], 2, '.', ''),
                    $stat['peak_slot'],
                ]);
            }
            fputcsv($handle, []);

            // Itemized Slot Utilizations
            fputcsv($handle, ['--- ITEMIZED COURT BOOKING SESSIONS ---']);
            fputcsv($handle, [
                'Date',
                'Court Name',
                'Start Time',
                'End Time',
                'Duration (Hours)',
                'Booking Reference',
                'Customer Name',
                'Booking Type',
                'Attendance Status',
            ]);

            foreach ($courts as $court) {
                foreach ($court->bookings as $booking) {
                    $hours = $this->calculateBookingHours($booking);
                    fputcsv($handle, [
                        $booking->date,
                        $court->court_name,
                        $booking->start_time,
                        $booking->end_time,
                        number_format($hours, 2, '.', ''),
                        $booking->reference_number ?? ('BK-' . $booking->id),
                        $booking->user->name ?? $booking->customer_name ?? 'Guest Customer',
                        ucfirst(str_replace('_', ' ', $booking->booking_type ?? 'online')),
                        ucfirst($booking->booking_status),
                    ]);
                }
            }

            fclose($handle);
        }, $filename, [
            'Content-Type' => 'text/csv; charset=UTF-8',
            'Content-Disposition' => "attachment; filename=\"{$filename}\"",
        ]);
    }

    /**
     * Calculate booking duration in hours.
     */
    public function calculateBookingHours(Booking $booking): float
    {
        if (empty($booking->start_time) || empty($booking->end_time)) {
            return 1.0;
        }

        try {
            $start = Carbon::parse($booking->start_time);
            $end = Carbon::parse($booking->end_time);
            $diffMins = abs($start->diffInMinutes($end));
            return $diffMins > 0 ? round($diffMins / 60, 2) : 1.0;
        } catch (\Throwable $e) {
            return 1.0;
        }
    }

    /**
     * Determine the peak time slot.
     */
    protected function determinePeakSlot($bookings): string
    {
        if ($bookings->isEmpty()) {
            return 'N/A';
        }

        $frequencies = [];
        foreach ($bookings as $b) {
            if (empty($b->start_time) || empty($b->end_time)) {
                continue;
            }
            try {
                $start = Carbon::parse($b->start_time)->format('g:i A');
                $end = Carbon::parse($b->end_time)->format('g:i A');
                $slotKey = "{$start} - {$end}";
                $frequencies[$slotKey] = ($frequencies[$slotKey] ?? 0) + 1;
            } catch (\Throwable $e) {
                continue;
            }
        }

        if (empty($frequencies)) {
            return 'N/A';
        }

        arsort($frequencies);
        return array_key_first($frequencies);
    }
}
