<x-admin-layout>
    <x-slot name="heading">Overview</x-slot>

    <div class="mb-8 flex flex-col justify-between gap-4 sm:flex-row sm:items-end">
        <div>
            <p class="text-sm text-slate-500">Good morning, {{ Str::before(Auth::user()->name, ' ') }}. Here is the pulse of your club.</p>
        </div>
        <a href="{{ route('admin.courts.create') }}" class="inline-flex items-center justify-center rounded-xl bg-slate-900 px-4 py-3 text-xs font-bold uppercase tracking-[0.14em] text-white transition hover:bg-lime-400 hover:text-slate-950">+ Add court</a>
    </div>

    <div class="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
        <div class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div class="flex items-start justify-between"><span class="text-xs font-bold uppercase tracking-wider text-slate-400">Month revenue</span><span class="rounded-lg bg-lime-100 px-2 py-1 text-xs font-bold text-lime-700">PHP</span></div><p class="mt-4 text-3xl font-extrabold tracking-tight">₱{{ number_format($monthlyRevenue, 2) }}</p><p class="mt-2 text-xs {{ $revenueChange !== null && $revenueChange >= 0 ? 'text-lime-700' : 'text-slate-400' }}">{{ $revenueChange !== null ? ($revenueChange >= 0 ? '+' : '') . $revenueChange . '% vs last month' : 'No prior month data' }}</p></div>
        <div class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div class="flex items-start justify-between"><span class="text-xs font-bold uppercase tracking-wider text-slate-400">Active courts</span><span class="rounded-lg bg-sky-50 px-2 py-1 text-xs font-bold text-sky-700">LIVE</span></div><p class="mt-4 text-3xl font-extrabold tracking-tight">{{ $courts->where('court_status', 'available')->count() }}<span class="text-lg text-slate-300"> / {{ $courts->count() }}</span></p><p class="mt-2 text-xs text-slate-500">Available for booking</p></div>
        <div class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div class="flex items-start justify-between"><span class="text-xs font-bold uppercase tracking-wider text-slate-400">Today’s bookings</span><span class="rounded-lg bg-slate-100 px-2 py-1 text-xs font-bold text-slate-600">{{ $today->format('M j') }}</span></div><p class="mt-4 text-3xl font-extrabold tracking-tight">{{ $todayBookings->count() }}</p><p class="mt-2 text-xs text-slate-500">{{ $totalBookings }} total bookings</p></div>
        <div class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div class="flex items-start justify-between"><span class="text-xs font-bold uppercase tracking-wider text-slate-400">Pending payments</span><span class="rounded-lg bg-amber-50 px-2 py-1 text-xs font-bold text-amber-700">REVIEW</span></div><p class="mt-4 text-3xl font-extrabold tracking-tight">{{ $pendingPayments }}</p><p class="mt-2 text-xs text-slate-500">Need reconciliation</p></div>
    </div>

    <div class="mt-8 grid gap-6 xl:grid-cols-[1.35fr_0.65fr]">
        <section class="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm">
            <div class="flex items-center justify-between border-b border-slate-100 px-5 py-4"><div><h2 class="font-extrabold">Today on court</h2><p class="mt-1 text-xs text-slate-400">Live schedule for {{ $today->format('l, M j') }}</p></div><a href="{{ route('admin.courts.index') }}" class="text-xs font-bold text-lime-700 hover:text-lime-800">Manage courts →</a></div>
            @forelse($todayBookings as $booking)
                <div class="flex items-center gap-4 border-b border-slate-100 px-5 py-4 last:border-0"><div class="w-16 shrink-0"><p class="text-sm font-extrabold">{{ \Carbon\Carbon::parse($booking->start_time)->format('g:i') }}</p><p class="text-[11px] text-slate-400">{{ \Carbon\Carbon::parse($booking->end_time)->format('g:i A') }}</p></div><div class="h-10 w-1 rounded-full bg-lime-400"></div><div class="min-w-0 flex-1"><p class="truncate text-sm font-bold">{{ $booking->court?->court_name ?? 'Court removed' }}</p><p class="truncate text-xs text-slate-500">{{ $booking->user?->name ?? 'Guest player' }} · {{ ucfirst($booking->booking_status) }}</p></div><span class="rounded-full px-2.5 py-1 text-[10px] font-bold uppercase {{ $booking->booking_status === 'confirmed' ? 'bg-lime-100 text-lime-700' : 'bg-amber-100 text-amber-700' }}">{{ $booking->booking_status }}</span></div>
            @empty
                <div class="px-5 py-14 text-center"><p class="font-bold text-slate-700">The courts are quiet today.</p><p class="mt-1 text-sm text-slate-400">New bookings will appear here.</p></div>
            @endforelse
        </section>

        <section class="rounded-2xl border border-slate-200 bg-slate-900 p-5 text-white shadow-sm"><div class="flex items-center justify-between"><div><p class="text-xs font-bold uppercase tracking-wider text-slate-400">Court health</p><h2 class="mt-1 font-extrabold">Availability</h2></div><span class="text-xl text-lime-400">◉</span></div><div class="mt-6 space-y-4">@forelse($courts as $court)<div><div class="mb-2 flex items-center justify-between text-xs"><span class="font-semibold">{{ $court->court_name }}</span><span class="{{ $court->court_status === 'available' ? 'text-lime-400' : 'text-amber-300' }}">{{ ucfirst($court->court_status) }}</span></div><div class="h-2 overflow-hidden rounded-full bg-white/10"><div class="h-full rounded-full {{ $court->court_status === 'available' ? 'bg-lime-400' : 'bg-amber-300' }}" style="width: {{ $court->court_status === 'available' ? '100' : '35' }}%"></div></div></div>@empty<p class="text-sm text-slate-400">Add your first court to start tracking availability.</p>@endforelse</div></section>
    </div>

    <section class="mt-6 overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div class="flex items-center justify-between border-b border-slate-100 px-5 py-4"><div><h2 class="font-extrabold">Recent payments</h2><p class="mt-1 text-xs text-slate-400">Latest activity across the club</p></div><a href="{{ route('admin.finance') }}" class="text-xs font-bold text-lime-700 hover:text-lime-800">View financials →</a></div><div class="overflow-x-auto"><table class="w-full min-w-[600px] text-left text-sm"><thead class="bg-slate-50 text-[10px] uppercase tracking-wider text-slate-400"><tr><th class="px-5 py-3 font-bold">Reference</th><th class="px-5 py-3 font-bold">Player</th><th class="px-5 py-3 font-bold">Date</th><th class="px-5 py-3 font-bold">Status</th><th class="px-5 py-3 text-right font-bold">Amount</th></tr></thead><tbody>@forelse($recentPayments as $payment)<tr class="border-t border-slate-100"><td class="px-5 py-3 font-semibold">{{ $payment->ref_num ?: 'Payment #' . $payment->id }}</td><td class="px-5 py-3 text-slate-500">{{ $payment->booking?->user?->name ?? 'Unknown player' }}</td><td class="px-5 py-3 text-slate-500">{{ \Carbon\Carbon::parse($payment->date)->format('M j, Y') }}</td><td class="px-5 py-3"><span class="rounded-full bg-lime-100 px-2 py-1 text-[10px] font-bold uppercase text-lime-700">{{ $payment->payment_status }}</span></td><td class="px-5 py-3 text-right font-extrabold">₱{{ number_format($payment->amount, 2) }}</td></tr>@empty<tr><td colspan="5" class="px-5 py-10 text-center text-sm text-slate-400">No payments recorded yet.</td></tr>@endforelse</tbody></table></div></section>
</x-admin-layout>
