<x-admin-layout>
    <x-slot name="heading">Financials</x-slot>

    <div class="mb-8"><p class="text-sm text-slate-500">Track paid revenue, transaction mix, and recent payment activity.</p></div>
    <div class="grid gap-4 sm:grid-cols-3"><div class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><p class="text-xs font-bold uppercase tracking-wider text-slate-400">This month</p><p class="mt-3 text-3xl font-extrabold">₱{{ number_format($monthlyRevenue, 2) }}</p><p class="mt-2 text-xs text-slate-400">Paid revenue</p></div><div class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><p class="text-xs font-bold uppercase tracking-wider text-slate-400">Year to date</p><p class="mt-3 text-3xl font-extrabold">₱{{ number_format($yearRevenue, 2) }}</p><p class="mt-2 text-xs text-slate-400">{{ now()->format('Y') }} paid revenue</p></div><div class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><p class="text-xs font-bold uppercase tracking-wider text-slate-400">Transactions</p><p class="mt-3 text-3xl font-extrabold">{{ number_format($transactionCount) }}</p><p class="mt-2 text-xs text-slate-400">Successful payments</p></div></div>

    <div class="mt-6 grid gap-6 xl:grid-cols-[1.25fr_0.75fr]"><section class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div class="flex items-center justify-between"><div><h2 class="font-extrabold">Revenue trend</h2><p class="mt-1 text-xs text-slate-400">Last six months</p></div><span class="rounded-lg bg-lime-100 px-2 py-1 text-[10px] font-bold uppercase text-lime-700">Paid only</span></div><div class="mt-8 flex h-48 items-end gap-3 sm:gap-5">@php($maxRevenue = max($monthlyTotals->max('amount'), 1))@foreach($monthlyTotals as $month)<div class="flex flex-1 flex-col items-center gap-2"><div class="flex h-36 w-full items-end"><div class="w-full rounded-t-lg bg-lime-400 transition hover:bg-slate-900" style="height: {{ max(($month['amount'] / $maxRevenue) * 100, $month['amount'] > 0 ? 8 : 2) }}%" title="₱{{ number_format($month['amount'], 2) }}"></div></div><span class="text-[11px] font-bold text-slate-400">{{ $month['label'] }}</span></div>@endforeach</div></section><section class="rounded-2xl border border-slate-200 bg-slate-900 p-5 text-white shadow-sm"><h2 class="font-extrabold">Payment mix</h2><p class="mt-1 text-xs text-slate-400">Paid transactions by method</p><div class="mt-7 space-y-5">@forelse($methodTotals as $method)<div><div class="mb-2 flex items-center justify-between text-xs"><span class="font-bold">{{ ucfirst($method->payment_method) }}</span><span class="text-slate-400">₱{{ number_format($method->total, 2) }}</span></div><div class="h-2 rounded-full bg-white/10"><div class="h-full rounded-full bg-lime-400" style="width: {{ $methodTotals->max('total') > 0 ? ($method->total / $methodTotals->max('total')) * 100 : 0 }}%"></div></div></div>@empty<p class="text-sm text-slate-400">Payment mix appears after paid transactions are recorded.</p>@endforelse</div></section></div>

    <section class="mt-6 overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div class="border-b border-slate-100 px-5 py-4"><h2 class="font-extrabold">Payment ledger</h2><p class="mt-1 text-xs text-slate-400">Every recorded payment, newest first.</p></div><div class="overflow-x-auto"><table class="w-full min-w-[680px] text-left text-sm"><thead class="bg-slate-50 text-[10px] uppercase tracking-wider text-slate-400"><tr><th class="px-5 py-3 font-bold">Reference</th><th class="px-5 py-3 font-bold">Player</th><th class="px-5 py-3 font-bold">Method</th><th class="px-5 py-3 font-bold">Date</th><th class="px-5 py-3 font-bold">Status</th><th class="px-5 py-3 text-right font-bold">Amount</th></tr></thead><tbody>@forelse($payments as $payment)<tr class="border-t border-slate-100"><td class="px-5 py-4 font-semibold">{{ $payment->ref_num ?: 'Payment #' . $payment->id }}</td><td class="px-5 py-4 text-slate-500">{{ $payment->booking?->user?->name ?? 'Unknown player' }}</td><td class="px-5 py-4 text-slate-500">{{ ucfirst($payment->payment_method) }}</td><td class="px-5 py-4 text-slate-500">{{ \Carbon\Carbon::parse($payment->date)->format('M j, Y') }}</td><td class="px-5 py-4"><span class="rounded-full px-2 py-1 text-[10px] font-bold uppercase {{ $payment->payment_status === 'paid' ? 'bg-lime-100 text-lime-700' : 'bg-amber-100 text-amber-700' }}">{{ $payment->payment_status }}</span></td><td class="px-5 py-4 text-right font-extrabold">₱{{ number_format($payment->amount, 2) }}</td></tr>@empty<tr><td colspan="6" class="px-5 py-12 text-center text-sm text-slate-400">No payments recorded yet.</td></tr>@endforelse</tbody></table></div>@if($payments->hasPages())<div class="border-t border-slate-100 px-5 py-4">{{ $payments->links() }}</div>@endif</section>
</x-admin-layout>
