<x-admin-layout>
    <x-slot name="heading">Courts</x-slot>

    <div class="mb-8 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p class="text-sm text-slate-500">Keep your court inventory, pricing, and availability in one place.</p></div><a href="{{ route('admin.courts.create') }}" class="inline-flex items-center justify-center rounded-xl bg-slate-900 px-4 py-3 text-xs font-bold uppercase tracking-[0.14em] text-white transition hover:bg-lime-400 hover:text-slate-950">+ Add court</a></div>
    @if(session('status'))<div class="mb-5 rounded-xl border border-lime-200 bg-lime-50 px-4 py-3 text-sm font-semibold text-lime-800">{{ session('status') }}</div>@endif
    @if(session('error'))<div class="mb-5 rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm font-semibold text-red-700">{{ session('error') }}</div>@endif

    <div class="grid gap-4 sm:grid-cols-3"><div class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><p class="text-xs font-bold uppercase tracking-wider text-slate-400">Total courts</p><p class="mt-3 text-3xl font-extrabold">{{ $courts->count() }}</p></div><div class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><p class="text-xs font-bold uppercase tracking-wider text-slate-400">Available</p><p class="mt-3 text-3xl font-extrabold text-lime-600">{{ $courts->where('court_status', 'available')->count() }}</p></div><div class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><p class="text-xs font-bold uppercase tracking-wider text-slate-400">Maintenance</p><p class="mt-3 text-3xl font-extrabold text-amber-600">{{ $courts->where('court_status', 'maintenance')->count() }}</p></div></div>

    <section class="mt-6 overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div class="overflow-x-auto"><table class="w-full min-w-[700px] text-left text-sm"><thead class="bg-slate-50 text-[10px] uppercase tracking-wider text-slate-400"><tr><th class="px-5 py-3 font-bold">Court</th><th class="px-5 py-3 font-bold">Size</th><th class="px-5 py-3 font-bold">Rate / hour</th><th class="px-5 py-3 font-bold">Bookings</th><th class="px-5 py-3 font-bold">Status</th><th class="px-5 py-3 text-right font-bold">Actions</th></tr></thead><tbody>@forelse($courts as $court)<tr class="border-t border-slate-100"><td class="px-5 py-4"><div class="flex items-center gap-3"><span class="flex h-9 w-9 items-center justify-center rounded-xl bg-lime-100 text-sm font-extrabold text-lime-700">{{ strtoupper(substr($court->court_name, 0, 1)) }}</span><span class="font-extrabold">{{ $court->court_name }}</span></div></td><td class="px-5 py-4 text-slate-500">{{ $court->size ?: 'Standard' }}</td><td class="px-5 py-4 font-bold">₱{{ number_format($court->price_per_hour, 2) }}</td><td class="px-5 py-4 text-slate-500">{{ $court->bookings_count }}</td><td class="px-5 py-4"><span class="rounded-full px-2.5 py-1 text-[10px] font-bold uppercase {{ $court->court_status === 'available' ? 'bg-lime-100 text-lime-700' : ($court->court_status === 'maintenance' ? 'bg-amber-100 text-amber-700' : 'bg-slate-100 text-slate-600') }}">{{ $court->court_status }}</span></td><td class="px-5 py-4 text-right"><a href="{{ route('admin.courts.edit', $court) }}" class="font-bold text-slate-600 hover:text-slate-900">Edit</a>@if($court->bookings_count === 0)<form class="ml-3 inline" method="POST" action="{{ route('admin.courts.destroy', $court) }}" onsubmit="return confirm('Remove this court?')">@csrf @method('DELETE')<button class="font-bold text-red-500 hover:text-red-700">Delete</button></form>@endif</td></tr>@empty<tr><td colspan="6" class="px-5 py-14 text-center"><p class="font-bold text-slate-700">No courts yet.</p><p class="mt-1 text-sm text-slate-400">Add your first court to start taking bookings.</p></td></tr>@endforelse</tbody></table></div></section>
</x-admin-layout>
